//ARRAY PRINCIPAL////
let libros = [
    {id:1 ,titulo:"rayuela" ,autor:"julio cortázar" ,genero:"novela" ,precio:700 ,año:1967 ,stock:4 ,cantidad: 1, imagen:"rayuela.jpg" },
    {id:2 ,titulo:"ficciones" ,autor:"jorge luis borges" ,genero:"cuento" ,precio:500 ,año:1969 ,stock:3 ,cantidad: 1, imagen:"ficciones.jpg" },
    {id:3 ,titulo:"100 años de soledad" ,autor:"gabriel garcía márquez" ,genero:"novela" ,precio:630 ,stock:5,cantidad: 1,imagen:"100añosdesoledad.jpg" },
    {id:4 ,titulo:"yo el supremo" ,autor:"augusto roa bastos" ,genero:"novela" ,precio:800 ,año:1968 ,stock:2 ,cantidad: 1, imagen:"yoelsupremo.jpg" },
    {id:5 ,titulo:"la ciudad y los perros" ,autor:"mario vargas llosa" ,genero:"novela" ,precio:550 ,año:1966 ,stock:3 ,cantidad: 1, imagen:"laciudadylosperros.jpg" },
    {id:6 ,titulo:"bestiario" ,autor:"julio cortázar" ,genero:"cuento" ,precio:400 ,año: 1958,stock:2 ,cantidad: 1, imagen:"bestiario.jpg" },
    {id:7 ,titulo:"crónica de una muerte anunciada" ,autor:"gabriel garcía márquez" ,genero:"novela" ,precio:350 ,año:1968 ,stock:1 ,cantidad: 1, imagen:"cronica.jpg" },
    {id:8 ,titulo:"cuentos completos" ,autor:"roberto bolaño" ,genero:"cuento" ,precio:720 ,año:1984 ,stock:3 ,cantidad: 1, imagen:"cuentoscompletos.jpg" },
    {id:9 ,titulo:"paradiso" ,autor:"josé lezama lima" ,genero:"novela" ,precio:430 ,año:1968 ,stock:2 ,cantidad: 1, imagen:"paradiso.jpg" },
    {id:10 ,titulo:"obra reunida" ,autor:"juan rulfo" ,genero:"cuento" ,precio:530 ,año:1974 ,stock:5 ,cantidad: 1, imagen:"obrareunida.jpg" },
    {id:11 ,titulo:"la hojarasca" ,autor:"gabriel garcía márquez" ,genero:"cuento" ,precio:350 ,año:1965 ,stock:3 ,cantidad: 1, imagen:"lahojarasca.jpg" },
    {id:12 ,titulo:"cuentos de amor, locura y muerte" ,autor:"horacio quiroga" ,genero:"cuento" ,precio:280 ,año:1974 ,stock:6,cantidad: 1, imagen:"cuentosdeamor.jpg" },
    {id:13 ,titulo:"bodas de sangre" ,autor:"fernando garcía lorca" ,genero:"drama" ,precio:740 ,año:1972 ,stock:3 ,cantidad: 1, imagen:"bodasdesangre.jpg" },
    {id:14 ,titulo:"la casa verde" ,autor:"mario vargas llosa" ,genero:"novela" ,precio:630 ,año:1978 ,stock:2 ,cantidad: 1, imagen:"lacasaverde.jpg" },
    {id:15 ,titulo:"cuentos de la selva" ,autor:"horacio quiroga" ,genero:"cuento" ,precio:300 ,año:1965 ,stock:1 ,cantidad: 1, imagen:"cuentosdelaselva.jpg" },
    {id:16 ,titulo:"los premios" ,autor:"julio cortázar" ,genero:"novela" ,precio:850 ,año:1962 ,stock:2 ,cantidad: 1, imagen:"lospremios.jpg" },
    {id:17 ,titulo:"ensayo sobre la ceguera" ,autor:"josé saramago" ,genero:"novela" ,precio:650 ,año:1970 ,stock:2 ,cantidad: 1, imagen:"ensayosobre.jpg" },
    {id:18 ,titulo:"final del juego" ,autor:"julio cortázar" ,genero:"cuento" ,precio:250 ,año:1972 ,stock:1 ,cantidad: 1, imagen:"finaldeljuego.jpg" },
    {id:19 ,titulo:"el amor en tiempos del cólera" ,autor:"gabriel garcía márquez" ,genero:"novela" ,precio:550 ,año:1968 ,stock:3 ,cantidad: 1, imagen:"elamorentiempos.jpg" },
    {id:20 ,titulo:"inquisiciones" ,autor:"jorge luis borges" ,genero:"cuento" ,precio:420 ,año:1954 ,stock:4 ,cantidad: 1, imagen:"inquisiciones.jpg" },
    {id:21 ,titulo:"martín fierro" ,autor:"josé hernandez" ,genero:"poesía" ,precio:470 ,año:1952 ,stock:5 ,cantidad: 1, imagen:"martinfierro.jpg" },
    {id:22 ,titulo:"rimas y leyendas" ,autor:"gustavo adolfo bécquer" ,genero:"poesía" ,precio:540 ,año:1865 ,stock:2 ,cantidad: 1, imagen:"rimas.jpg" },
    {id:23 ,titulo:"la secta" ,autor:"camilla lackberg" ,genero:"novela" ,precio:750 ,año:2020 ,stock:8 ,cantidad: 1, imagen:"lasecta.jpg" },
    {id:24 ,titulo:"cien cuyes" ,autor:"gustavo rodríguez" ,genero:"novela" ,precio:640 ,año:2022 ,stock:5 ,cantidad: 1, imagen:"ciencuyes.jpg" },
    {id:25 ,titulo:"primera sangre" ,autor:"amelie nothomb" ,genero:"novela" ,precio:950 ,año:2021 ,stock:5 ,cantidad: 1, imagen:"primerasangre.jpg" },
    {id:26 ,titulo:"el ancho mundo" ,autor:"pierre lemaitre" ,genero:"novela" ,precio:780 ,año:2023 ,stock:4 ,cantidad: 1, imagen:"elanchomundo.jpg" },
    {id:27 ,titulo:"nosotros los vencidos" ,autor:"fernando butazzoni" ,genero:"novela" ,precio:990 ,año:2022,stock:6 ,cantidad: 1, imagen:"nosotros.jpg" },
    {id:28 ,titulo:"el perfume del rey" ,autor:"karine bernal" ,genero:"novela" ,precio:650 ,año:2022 ,stock:4 ,cantidad: 1, imagen:"perfume.jpg" },
    {id:29 ,titulo:"los adversarios" ,autor:"john grisman" ,genero:"novela" ,precio:890 ,año:2023 ,stock:3 ,cantidad: 1, imagen:"losadversarios.jpg" },
    {id:30 ,titulo:"bajo aguas oscuras" ,autor:"robert bryndza" ,genero:"novela" ,precio:740 ,año:2021 ,stock:6 ,cantidad: 1, imagen:"bajoaguas.jpg" },

]
 